spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/tienda_ropa_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

jwt.secret=clave_super_secreta_para_tienda_ropa_online_2026_segura
