spring.application.name=backend

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/tienda_ropa_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:clave_super_secreta_para_tienda_ropa_online_2026_segura}
